# Generated by Django 5.2.7 on 2025-10-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='testimoni/')),
                ('judul', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
