# Generated by Django 5.2.7 on 2025-10-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producttype_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_types/'),
        ),
    ]
