# Generated by Django 5.2.7 on 2025-10-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_producttype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='penanggung_jawab',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
