# Generated by Django 5.2.7 on 2025-10-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_producttype_penanggung_jawab'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_payment',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
